#!/usr/bin/ruby

# Load required modules
require 'time'

# Read all the logs in descending order
Dir.glob("#{Dir.home}/logthislogs/*").sort.reverse.each do |file|
    f = File.open(file,"r")
    f.each_line do |line|
        basename = File.basename(file,".txt").to_i
        time = Time.at(basename).localtime.to_s
        puts time + "\ ->\ " + line
    end
    f.close
end
